/**
 * LIVE RECALL TUNING — runs fixtures/recall-tuning.json against your real relayer in a THROWAWAY namespace
 * and prints distance distributions. Distances are retrieval signals, not truth values; thresholds chosen
 * here are starting points for YOUR memory style. Writes docs/RECALL_TUNING.md.
 * Each run writes a handful of real memories (blobs) to a throwaway namespace — run it sparingly.
 */
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { MemWal } from "@mysten-incubation/memwal";
import { ScopedMemory } from "../lib/memory/scoped";
import type { WalrusClient } from "../lib/memory/types";

const key = process.env.MEMWAL_PRIVATE_KEY;
const accountId = process.env.MEMWAL_ACCOUNT_ID;
if (!key || !accountId) { console.log("MEMWAL_PRIVATE_KEY and MEMWAL_ACCOUNT_ID required."); process.exit(1); }
const serverUrl = process.env.MEMWAL_SERVER_URL ?? "https://relayer.memory.walrus.xyz";
const fx = JSON.parse(readFileSync("fixtures/recall-tuning.json", "utf8")) as {
  seeds: Array<{ id: string; fact: string }>;
  dedupePairs: Array<{ seed: string; candidate: string; category: string }>;
  queries: Array<{ q: string; relevant: string[] }>;
};

const client = MemWal.create({ key, accountId, serverUrl }) as unknown as WalrusClient;
const store = new ScopedMemory(randomBytes(16).toString("hex"), {
  client, memoryEnv: "tune", serverUrlNetwork: "Custom", tokenSecret: randomBytes(32).toString("hex"),
  settings: { maxResults: 10, maxDistance: 2, recallTimeoutMs: 20000, waitTimeoutMs: 90000, countMaxPages: 5 },
});

for (const s of fx.seeds) {
  const r = await store.save(s.fact, { clientMessageId: crypto.randomUUID(), mode: "wait" });
  if (r.state !== "saved") { console.log(`seed "${s.id}" not confirmed (${r.state}); aborting.`); process.exit(1); }
}
await new Promise((r) => setTimeout(r, 4000));

const stats = (xs: number[]) => xs.length ? { n: xs.length, min: Math.min(...xs), median: [...xs].sort((a, b) => a - b)[Math.floor(xs.length / 2)], max: Math.max(...xs) } : null;
const fmt = (s: ReturnType<typeof stats>) => s ? `n=${s.n} min=${s.min.toFixed(3)} median=${s.median.toFixed(3)} max=${s.max.toFixed(3)}` : "n/a";

// dedupe pairs: distance from the CANDIDATE text to its seed memory
const byCat: Record<string, number[]> = {};
for (const p of fx.dedupePairs) {
  const seedText = fx.seeds.find((s) => s.id === p.seed)!.fact;
  const r = await store.recall(p.candidate, { limit: 10, maxDistance: 2 });
  const hit = r.memories.find((m) => m.text === seedText);
  if (hit) (byCat[p.category] ??= []).push(hit.distance);
}
// queries: distance of relevant vs irrelevant seeds
const rel: number[] = []; const irrel: number[] = [];
for (const q of fx.queries) {
  const r = await store.recall(q.q, { limit: 10, maxDistance: 2 });
  for (const m of r.memories) {
    const id = fx.seeds.find((s) => s.fact === m.text)?.id;
    (id && q.relevant.includes(id) ? rel : irrel).push(m.distance);
  }
}
const nearDup = [...(byCat.exact_duplicate ?? []), ...(byCat.paraphrase ?? [])];
const notDup = [...(byCat.related ?? []), ...(byCat.unrelated ?? [])];
const dedupeSuggest = nearDup.length && notDup.length && Math.max(...nearDup) < Math.min(...notDup) ? ((Math.max(...nearDup) + Math.min(...notDup)) / 2) : null;
const recallSuggest = rel.length && irrel.length && Math.max(...rel) < Math.min(...irrel) ? ((Math.max(...rel) + Math.min(...irrel)) / 2) : null;

const report = [
  "# Recall tuning (generated by scripts/tune-recall.ts against the live relayer)", "",
  `Run: ${new Date().toISOString()} · relayer: ${new URL(serverUrl).host}`, "",
  "## Candidate -> seed distances by category (dedupe)",
  ...Object.entries(byCat).map(([c, xs]) => `- ${c}: ${fmt(stats(xs))}`), "",
  "## Query -> seed distances (recall)", `- relevant: ${fmt(stats(rel))}`, `- irrelevant: ${fmt(stats(irrel))}`, "",
  "## Suggested starting values",
  dedupeSuggest !== null ? `- MEMORY_DEDUPE_DISTANCE ≈ ${dedupeSuggest.toFixed(3)} (separates exact/paraphrase from related/unrelated in this fixture)` : "- MEMORY_DEDUPE_DISTANCE: the categories overlap in this fixture; keep the conservative default (0.2) and inspect the distributions above.",
  recallSuggest !== null ? `- MEMORY_MAX_DISTANCE ≈ ${recallSuggest.toFixed(3)} (separates relevant from irrelevant in this fixture)` : "- MEMORY_MAX_DISTANCE: relevant/irrelevant overlap in this fixture; keep the default (0.55) and inspect the distributions above.",
  "- Contradictory pairs are deliberately NOT treated as duplicates: corrections bypass semantic dedupe by design.", "",
  "Distances are retrieval signals, not truth values. This fixture is small; re-run with your own memory style.",
].join("\n");
console.log(report);
writeFileSync("docs/RECALL_TUNING.md", report + "\n");
(client as unknown as { destroy?: () => void }).destroy?.();
