/**
 * LIVE WALRUS MAINNET TEST — performs REAL operations with REAL credentials. Each run writes ONE real
 * memory (one real Walrus blob). Do not loop it; genuine submission activity should come from real app use.
 * Output is prefixed "LIVE WALRUS MAINNET TEST"; the mocked suite can never print that.
 */
import { randomBytes } from "node:crypto";
import { writeFileSync, mkdirSync } from "node:fs";
import { MemWal } from "@mysten-incubation/memwal";
import { ScopedMemory } from "../lib/memory/scoped";
import type { WalrusClient } from "../lib/memory/types";

const P = "LIVE WALRUS MAINNET TEST";
const MAINNET_HOST = "relayer.memory.walrus.xyz";
const key = process.env.MEMWAL_PRIVATE_KEY;
const accountId = process.env.MEMWAL_ACCOUNT_ID;
const serverUrl = process.env.MEMWAL_SERVER_URL ?? `https://${MAINNET_HOST}`;
const lines: string[] = [];
let failed = 0;
const say = (s: string) => { console.log(`[${P}] ${s}`); lines.push(s); };
const pass = (s: string) => say(`PASS  ${s}`);
const fail = (s: string) => { failed++; say(`FAIL  ${s}`); };
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

if (!key || !accountId) { console.log(`[${P}] FAIL  MEMWAL_PRIVATE_KEY and MEMWAL_ACCOUNT_ID are required (mainnet credentials from memory.walrus.xyz).`); process.exit(1); }
const host = new URL(serverUrl).host;
if (host !== MAINNET_HOST) { console.log(`[${P}] FAIL  refusing to run: relayer host is "${host}", not the mainnet relayer ${MAINNET_HOST}. Staging results are not mainnet evidence.`); process.exit(1); }

const client = MemWal.create({ key, accountId, serverUrl }) as unknown as WalrusClient & { compatibility(): Promise<unknown> };
const mk = (userId: string) => new ScopedMemory(userId, {
  client, memoryEnv: "verify", serverUrlNetwork: "Mainnet", tokenSecret: randomBytes(32).toString("hex"),
  settings: { maxResults: 5, maxDistance: 0.9, recallTimeoutMs: 15000, waitTimeoutMs: 90000, countMaxPages: 5 },
});

const runId = new Date().toISOString();
say(`run ${runId} relayer=${host}`);

// 1. health / compatibility / write_ready
const h = await client.health();
h.status === "ok" || h.status === "healthy" ? pass(`relayer health: ${h.status}, version=${h.relayerVersion ?? h.version ?? "n/a"}`) : fail(`relayer health: ${h.status}`);
if (h.write_ready === false) fail("relayer reports write_ready=false"); else pass(`write_ready=${String(h.write_ready)}`);
try { await client.compatibility(); pass("SDK/relayer compatibility check passed"); } catch (e) { fail(`compatibility failed: ${(e as Error).name}`); }

// 2. write a real memory and wait for completion
const userA = randomBytes(16).toString("hex");
const userB = randomBytes(16).toString("hex");
const A = mk(userA);
const fact = `User is verifying the Recall chatbot on Walrus Mainnet (run ${runId}).`;
const saved = await A.save(fact, { clientMessageId: crypto.randomUUID(), mode: "wait" });
if (saved.state === "saved") pass(`write confirmed by rememberAndWait; memory id=${saved.memoryId}; blob id=${saved.blobId ?? "(none reported)"}`);
else { fail(`write not confirmed: state=${saved.state} code=${saved.errorCode}`); }

// 3. recall (bounded wait for indexing lag)
const query = "verifying the Recall chatbot on Walrus";
let found = false;
for (let i = 0; i < 6 && !found; i++) {
  const r = await A.recall(query, { maxDistance: 1.5 });
  found = r.memories.some((m) => m.text === fact);
  if (!found) await sleep(2500);
}
found ? pass("memory became recallable in the correct namespace") : fail("memory not recalled within the bounded wait (indexing lag or failure)");

// 4. a fresh 'conversation' (new store instance, no history) recalls it
const fresh = mk(userA);
const again = await fresh.recall(query, { maxDistance: 1.5 });
again.memories.some((m) => m.text === fact) ? pass("fresh store instance (no chat history) recalled it") : fail("fresh instance did not recall it");

// 5. isolation: another namespace must NOT see it
const other = await mk(userB).recall(query, { maxDistance: 1.5 });
other.memories.length === 0 ? pass("a different user's namespace did NOT recall it (isolation holds)") : fail(`ISOLATION FAILURE: other namespace returned ${other.memories.length} result(s)`);

say(failed ? `${failed} check(s) FAILED` : "ALL CHECKS PASSED");
if (saved.state === "saved") {
  mkdirSync("docs", { recursive: true });
  writeFileSync("docs/mainnet-evidence.md", [
    "# Mainnet evidence (generated by scripts/verify-mainnet.ts)", "",
    `Run: ${runId}`, `Relayer host: ${host}`, `Memory ID: ${saved.memoryId ?? "n/a"}`, `Blob ID: ${saved.blobId ?? "none reported by the SDK"}`, "",
    "```", ...lines, "```", "", "Values above are copied from real SDK/relayer responses. Nothing is simulated.",
  ].join("\n"));
  console.log(`[${P}] wrote docs/mainnet-evidence.md`);
}
(client as unknown as { destroy?: () => void }).destroy?.();
process.exit(failed ? 1 : 0);
